api/urls.py
from django.urls import include, path
from . import views
from rest_framework import routers

router = routers.DefaultRouter()

router.register(r'', views.task_view)

urlpatterns = [
    path('', include(router.urls))
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name="index"),
    path('update/<str:pk>/', views.update_task, name="update"),
    path('delete/<str:pk>/', views.delete_task, name="delete")
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tasks.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls)
]

api/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['completed']

    def __str__(self):
        return self.title

tasks/forms.py
'''
Se importa las librerias necesarias para tener el template
del form
'''
from django import forms
from django.forms import ModelForm
from .models import *


#Las templates se deben ser class based
class TaskForm(forms.ModelForm):

    #En el class meta se define que model va a usar el form
    class Meta:

        #Se define qel modelo es el de las tareas
        model = Task

        '''
        Se pasan todos los campos del modelo
        tareas:
        Title
        Completed
        created
        '''
        fields = '__all__'

api/views.py
from django.shortcuts import render
from rest_framework import serializers, viewsets
from .serializers import TaskSerializer
from tasks.models import Task
# Create your views here.

class task_view(viewsets.ModelViewSet):
    serializer_class = TaskSerializer
    queryset = Task.objects.all()

tasks/views.py
from django.shortcuts import redirect, render
from .models import *
from .forms import *
# Create your views here.
def index(request):
    tasks = Task.objects.all()

    form = TaskForm()


    '''
    Se verifica que el metodo sea POST, es decir,
    que el formulario esta enviado información.
    '''
    if request.method == 'POST':
        form =  TaskForm(request.POST)
        '''
        El template verfica si el formulario
        esta correcto, si es asi lo "Guarda"
        sino lanza advertencias, al guardar
        el form se envia automaticamente
        a la base de datos
        '''
        
        if form.is_valid():
            form.save()
        '''
        Una vez el formulario se haya enviado
        se redirecciona a la misma pagina
        pero con el metodo GET
        '''
        return redirect('/')

    context = {
        'tasks': tasks,
        'form': form
    }
    return render(request, 'tasks/list.html', context)

def update_task(request, pk):
    task = Task.objects.get(id=pk)

    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
        return redirect('/')

    context = {'form':form}

    return render(request, 'tasks/update_task.html', context)

def delete_task(request, pk):
    task = Task.objects.get(id=pk)
    if request.method == 'POST':
        task.delete()
        return redirect('/')

    context = {
        'task': task
    }

    return render(request, 'tasks/delete_task.html', context)

tasks/templates/tasks/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo App</title>
    <link rel="stylesheet" type="text/css" href="{% static 'tasks/css/styles.css' %}">
</head>
<body>
    {% block body %}

    {% endblock body %}
</body>
</html>

tasks/templates/tasks/delete_task.html
{% extends 'tasks/base.html' %}

{% block body %}
<div class="list-container">
    <div class="delete-container">
        <h1 class="delete-title">Delete task</h1>

        <p class="delete-text">¿Seguro que quiere eliminar la tarea "{{task}}"?</p>


        <form action="" method="POST" class="deleteTask">
            {% csrf_token %}
            <input type="submit" value="Eliminar Tarea">
        </form>
        <a class="delete-cancel"href="{% url 'tasks:index'%}">Cancelar</a>
    </div>
</div>
{% endblock body %}

tasks/templates/tasks/list.html
{% extends 'tasks/base.html' %}

{% block body %}
<div class="list-container">
    <div class="box-container">

        <div class="title-container"> 
            <h1 class="title">To-Do</h1>
            <a href="">Logout</a>
        </div>
        
        
        <form method="POST" action="/" class="addTask">
            {% csrf_token %}
            {{ form.title }}
            <input type="submit" value="Añadir">
        </form>

        <div class="tasks">
            {% for task in tasks %}
                {% if task.completed == True %}
                <div class="tasks-item">

                    <span>&#9989;   {{ task }}</span>
                                       
                    <div class="edit-tasks">
                        <a href="{% url 'tasks:update' task.id%}">✏️</a>
                        <a href="{% url 'tasks:delete' task.id%}">&#10060;</a>
                    </div>
                </div>
                {% else %}
                <div class="tasks-item-uncomplete">
                
                    <span>&#9940;   {{ task }}</span>

                    <div class="edit-tasks">
                        <a href="{% url 'tasks:update' task.id%}">✏️</a>
                        <a href="{% url 'tasks:delete' task.id%}">&#10060;</a>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock body %}

tasks/templates/tasks/update_task.html
{% extends 'tasks/base.html' %}

{% block body %}

<div class="list-container">
    <div class="actualizar-tarea">
        <h3 >Update Task</h3>
        <form class="updateTask" method="POST" action="">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Actualizar">
        </form>
        <a class="delete-cancel"href="{% url 'tasks:index'%}">Cancelar</a>
    </div>
</div>

{% endblock body %}